export type PermissionsMap = Record<string, string[]>;

export const permissionRoles = [
  { label: 'Org Owner', id: 'org_owner' },
  { label: 'Org Admin', id: 'org_admin' },
  { label: 'Billing Admin', id: 'billing_admin' },
  { label: 'User Admin', id: 'user_admin' },
  { label: 'Advisor', id: 'advisor_admin' },
  { label: 'Viewer', id: 'viewer' },
  { label: 'SSO Admin', id: 'sso_admin' },
];

export const permissionsMap: PermissionsMap = {
  org_owner: [
    'org:*',
    'users:*',
    'billing:*',
    'career:*',
    'sso:*',
    'reports:*',
    'admins:*',
  ],
  org_admin: [
    'reports:view',
    'org:view',
    'org:update_details',
    'org:update_logo',
    'org:view_domains',
    'org:manage_domains',
    'org:manage_seats',
    'org:manage_admins',
    'admins:view',
    'admins:manage',
    'users:list',
    'users:create',
    'users:add',
    'users:assign_roles',
    'users:remove',
    'users:view_profile',
  ],
  billing_admin: [
    'billing:view',
    'billing:view_invoices',
    'billing:update_payment_method',
    'billing:update_plan',
  ],
  user_admin: [
    'reports:view',
    'users:list',
    'users:create',
    'users:add',
    'users:assign_roles',
    'users:remove',
    'users:view_profile',
  ],
  advisor: [
    'reports:view',
    'career:view',
    'career:edit',
    'career:comment',
    'career:export',
    'users:list',
  ],
  viewer: ['reports:view', 'career:view', 'users:list'],
  sso_admin: ['sso:view', 'sso:configure', 'sso:disable'],
};
