import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const plans = [
  {
    key: 'free',
    level: 1,
    name: 'Legacy Free',
    priceCents: 0,
    interval: 'month',
    priceCentsYear: 0,
    description:
      'Perfect for job seekers who want a smarter way to organize and track their career progress',
    featureList: [
      'Add Achievements',
      'Schedule Jobs',
      'Track Job Applications',
    ],
    features: [
      'achievements:create',
      'achievements:update',
      'achievements:download',
      'achievements:print',
      'meeting:view',
      'meeting:create',
      'coverLetter:download',
      'jobApp:create',
      'jobApp:update',
      'jobApp:delete',
      'jobPosition:create',
      'jobPosition:update',
      'jobPosition:delete',
      'education:create',
      'education:update',
      'education:delete',
      'skills:edit',
    ],
    type: 'user',
  },
  {
    key: 'pro-beta',
    level: 2,
    name: 'Premium',
    priceCents: 799,
    interval: 'month',
    priceCentsYear: 7999,
    description: 'For people who want to elevate there career',
    featureList: [
      'Meeting Cheat Sheet',
      'Meeting Prep',
      'Reminder Achievement Emails',
    ],
    features: [
      'meeting:cheatsheet',
      'meeting:prep',
      'meeting:view',
      'meeting:create',
      'meeting:update',
      'meetingNotes:download',
      'resume:create',
      'resume:update',
      'resume:delete',
      'resume:duplicate',
      'achievements:create',
      'achievements:update',
      'achievements:download',
      'achievements:print',
      'meeting:view',
      'meeting:create',
      'coverLetter:download',
      'jobApp:create',
      'jobApp:update',
      'jobApp:delete',
      'jobPosition:create',
      'jobPosition:update',
      'jobPosition:delete',
      'education:create',
      'education:update',
      'education:delete',
      'skills:edit',
    ],
    type: 'user',
  },
  {
    key: 'pro-edu',
    level: 2,
    name: 'Premium',
    priceCents: 299,
    interval: 'month',
    priceCentsYear: 2999,
    features: [
      'meeting:cheatsheet',
      'meeting:prep',
      'meeting:view',
      'meeting:create',
      'meeting:update',
      'meetingNotes:download',
      'resume:create',
      'resume:update',
      'resume:delete',
      'resume:duplicate',
      'achievements:create',
      'achievements:update',
      'achievements:download',
      'achievements:print',
      'meeting:view',
      'meeting:create',
      'coverLetter:download',
      'jobApp:create',
      'jobApp:update',
      'jobApp:delete',
      'jobPosition:create',
      'jobPosition:update',
      'jobPosition:delete',
      'education:create',
      'education:update',
      'education:delete',
      'skills:edit',
    ],
    description: 'For people who want to elevate there career',
    featureList: [
      'Meeting Cheat Sheet',
      'Meeting Prep',
      'Reminder Achievement Emails',
    ],
    type: 'user',
  },
  {
    key: 'pro',
    level: 2,
    name: 'Premium',
    features: [
      'meeting:cheatsheet',
      'meeting:prep',
      'meeting:view',
      'meeting:create',
      'meeting:update',
      'meetingNotes:download',
      'resume:create',
      'resume:update',
      'resume:delete',
      'resume:duplicate',
      'achievements:create',
      'achievements:update',
      'achievements:download',
      'achievements:print',
      'meeting:view',
      'meeting:create',
      'coverLetter:download',
      'jobApp:create',
      'jobApp:update',
      'jobApp:delete',
      'jobPosition:create',
      'jobPosition:update',
      'jobPosition:delete',
      'education:create',
      'education:update',
      'education:delete',
      'skills:edit',
    ],
    priceCents: 799,
    interval: 'month',
    priceCentsYear: 7999,
    description: 'For people who want to elevate there career',
    featureList: [
      'Meeting Cheat Sheet',
      'Meeting Prep',
      'Reminder Achievement Emails',
    ],
    type: 'user',
  },
  {
    key: 'organization',
    level: null,
    name: 'Organization',
    priceCents: 1000,
    interval: 'per 100',
    description:
      'For organizations to provide subscriptions to large organizations of people',
    featureList: ['People Management', 'Subscription Management'],
    type: 'org',
    maxAdminSeats: 100,
  },
  {
    key: 'org-premium',
    level: null,
    name: 'Organization Premium',
    priceCents: 0,
    interval: 'Selected',
    description:
      'For organizations to provide premium subscriptions to large organizations of peopled.',
    featureList: ['People Management', 'Subscription Management'],
    userKey: 'pro',
    type: 'org',
    maxAdminSeats: 100,
  },
  {
    key: 'org-basic',
    level: null,
    name: 'Organization',
    priceCents: 0,
    interval: 'Selected',
    description:
      'For organizations to provide subscriptions to large organizations of peopled. ',
    featureList: ['People Management', 'Subscription Management'],
    userKey: 'free',
    type: 'org',
    maxAdminSeats: 100,
  },
  {
    key: 'coach-starter',
    level: null,
    name: 'Coach Starter',
    description:
      'Everything a solo coach needs to manage clients simply and professionally.',
    priceCents: 1499,
    priceCentsSeats: null,
    interval: 'Month',
    featureList: ['People Management', 'Subscription Management'],
    userKey: 'pro',
    features: ['org:createPromoCode'],
    hasMeteredSeats: false,
    type: 'coach',
    maxAdminSeats: 1,
    maxSeats: 20,
  },
  {
    key: 'coach-growth',
    level: null,
    name: 'Coach Growth',
    priceCents: 4999,
    priceCentsSeats: null,
    interval: 'Month',
    description:
      'Built for coaches scaling their practice with more clients and light team support.',
    featureList: ['People Management', 'Subscription Management'],
    userKey: 'pro',
    features: ['org:createCustomPromoCode', 'org:createPromoCode'],
    type: 'coach',
    hasMeteredSeats: false,
    maxAdminSeats: 50,
    maxSeats: 75,
  },
  {
    key: 'coach-agency',
    level: null,
    name: 'Coach Agency',
    priceCents: 19999,
    priceCentsSeats: null,
    interval: 'Month',
    description:
      'A full client-management platform for high-volume teams and agencies.',
    featureList: ['People Management', 'Subscription Management'],
    features: ['org:createCustomPromoCode', 'org:createPromoCode'],
    userKey: 'pro',
    type: 'coach',
    hasMeteredSeats: false,
    maxAdminSeats: 100,
    maxSeats: 250,
  },
];

async function main() {
  console.log('Seeding plans…');

  for (const plan of plans) {
    await prisma.plan.upsert({
      where: { key: plan.key }, // must have unique constraint on "key"
      update: {
        key: plan.key,
        level: plan.level,
        name: plan.name,
        priceCents: plan.priceCents,
        interval: plan.interval,
        priceCentsYear: plan.priceCentsYear,
        priceCentsSeats: plan.priceCentsSeats,
        description: plan.description,
        featureList: plan.featureList,
        userKey: plan.userKey,
        hasMeteredSeats: plan.hasMeteredSeats,
        type: plan.type,
        maxAdminSeats: plan.maxAdminSeats,
        maxSeats: plan.maxSeats,
        features: plan.features || [],
      },
      create: plan,
    });
  }

  console.log('✅ Plans loaded / updated.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
